# Generated by Django 4.0.3 on 2022-03-12 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('doc_no', models.CharField(blank=True, max_length=64, null=True)),
                ('doc_date', models.DateField(blank=True, null=True)),
                ('doc_from', models.CharField(blank=True, max_length=200, null=True)),
                ('doc_to', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.TextField()),
                ('active', models.IntegerField()),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('filepath', models.CharField(blank=True, max_length=255, null=True)),
                ('create_by', models.ForeignKey(blank=True, db_column='create_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='create_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doc',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DocCredential',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'doc_credential',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DocStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'doc_status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DocUrgent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'doc_urgent',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.CharField(blank=True, max_length=64, null=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='DocTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('action_by', models.ForeignKey(blank=True, db_column='action_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='doc_record.doc')),
                ('doc_status', models.ForeignKey(db_column='doc_status', on_delete=django.db.models.deletion.DO_NOTHING, to='doc_record.docstatus')),
            ],
            options={
                'db_table': 'doc_trace',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DocSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_no', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='doc_record.doc')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group')),
            ],
            options={
                'db_table': 'doc_send',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DocReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_no', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='doc_record.doc')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group')),
            ],
            options={
                'db_table': 'doc_receive',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='doc',
            name='credential',
            field=models.ForeignKey(blank=True, db_column='credential', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='doc_record.doccredential'),
        ),
        migrations.AddField(
            model_name='doc',
            name='update_by',
            field=models.ForeignKey(blank=True, db_column='update_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doc',
            name='urgent',
            field=models.ForeignKey(blank=True, db_column='urgent', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='doc_record.docurgent'),
        ),
    ]
