# Generated by Django 4.0.3 on 2022-03-19 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doc_record', '0003_alter_doc_create_by_alter_doc_credential_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctrace',
            name='action_by',
        ),
        migrations.AddField(
            model_name='doctrace',
            name='action_to',
            field=models.ForeignKey(blank=True, db_column='action_to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trace_action_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctrace',
            name='create_by',
            field=models.ForeignKey(blank=True, db_column='create_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trace_create_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
