# Generated by Django 4.0.3 on 2022-03-20 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('doc_record', '0004_remove_doctrace_action_by_doctrace_action_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docreceive',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doc_record.doctrace'),
        ),
        migrations.AlterField(
            model_name='doctrace',
            name='action_to',
            field=models.ForeignKey(blank=True, db_column='action_to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trace_action_to', to='auth.group'),
        ),
    ]
