# Generated by Django 4.0.3 on 2022-03-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_record', '0005_alter_docreceive_action_alter_doctrace_action_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docreceive',
            name='action',
        ),
        migrations.AddField(
            model_name='docreceive',
            name='action',
            field=models.ManyToManyField(blank=True, null=True, to='doc_record.doctrace'),
        ),
    ]
