# Generated by Django 4.0.3 on 2022-03-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('doc_record', '0006_remove_docreceive_action_docreceive_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docreceive',
            name='group',
        ),
        migrations.AlterField(
            model_name='docreceive',
            name='action',
            field=models.ManyToManyField(blank=True, null=True, to='auth.group'),
        ),
    ]
