# Generated by Django 4.0.3 on 2022-03-20 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('doc_record', '0007_remove_docreceive_group_alter_docreceive_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='docreceive',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_group', to='auth.group'),
        ),
    ]
