# Generated by Django 4.0.3 on 2022-03-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('doc_record', '0008_docreceive_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='docreceive',
            name='send_to',
            field=models.ManyToManyField(blank=True, null=True, to='auth.group'),
        ),
        migrations.RemoveField(
            model_name='docreceive',
            name='action',
        ),
        migrations.AddField(
            model_name='docreceive',
            name='action',
            field=models.TextField(blank=True, null=True),
        ),
    ]
