# Generated by Django 4.0.3 on 2022-03-21 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('doc_record', '0009_docreceive_send_to_remove_docreceive_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='filepath',
        ),
        migrations.AlterField(
            model_name='docreceive',
            name='send_to',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
        migrations.CreateModel(
            name='DocFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='upload/doc/%Y%m%d')),
                ('doc', models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='doc_record.doc')),
            ],
            options={
                'db_table': 'doc_file',
                'managed': True,
            },
        ),
    ]
