# Generated by Django 4.0.3 on 2022-03-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('doc_record', '0009_docreceive_send_to_remove_docreceive_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='upload/doc/%Y%m%d')),
            ],
        ),
        migrations.RemoveField(
            model_name='doc',
            name='filepath',
        ),
        migrations.AlterField(
            model_name='docreceive',
            name='send_to',
            field=models.ManyToManyField(to='auth.group'),
        ),
        migrations.AddField(
            model_name='doc',
            name='file',
            field=models.ManyToManyField(to='doc_record.file'),
        ),
    ]
