# Generated by Django 4.0.3 on 2022-03-24 05:30

from django.db import migrations, models
import doc_record.models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_record', '0011_alter_docfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctrace',
            name='success',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='docfile',
            name='file',
            field=models.FileField(upload_to=doc_record.models.update_doc_filename),
        ),
    ]
