# Generated by Django 4.0.3 on 2022-03-25 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('doc_record', '0014_doctrace_action_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='docsend',
            name='send_to',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='docreceive',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receive_group', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='docsend',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_group', to='auth.group'),
        ),
    ]
