# Generated by Django 4.0.3 on 2022-03-29 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('doc_record', '0015_docsend_send_to_alter_docreceive_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.IntegerField(blank=True, null=True)),
                ('specific', models.BooleanField(default=False)),
                ('action', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doc_record.doc')),
                ('issue_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_group', to='auth.group')),
            ],
            options={
                'db_table': 'doc_order',
                'managed': True,
            },
        ),
    ]
