# Generated by Django 4.0.3 on 2022-04-04 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doc_record', '0016_docorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineNotifyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_notify_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'line_notify_token',
                'managed': True,
            },
        ),
    ]
