# Generated by Django 4.1.6 on 2023-03-19 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc_record', '0018_alter_unit_options_unit_parent_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'unit_level',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_level', to='doc_record.unitlevel'),
        ),
    ]
